apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:psAjxJocnRjB2tymL4aITQcGLvMs/HlB4Pn6wHY98Ynw2hPPU4xzUGzAw6NeHaFfyMDFy1NEdRNEf0vGBpmv7FF+Mf+5tJKY5v/rcbc3AZY7FJpmcdt4pVRbw3HxqY2vBa12Lc25D6bw/EhgXbl50YZsCP62SRkkIIerPi8KBWsuAWdKgsFDbwCQJJjBWWaSPV2vBTq18adTuY8A38r0VdVvW+fYdI9QnyWOjWmdpxsIjzsKH9gbfRtbHG/ZxycQJnSESJrpGyrN3uWQEvxpK+6B/eNc2HrIGgSqpkc32ulaIsrNfSNRDR6EWCE=,iv:q9iOOO2F32HcRlm+PBIDhqnxNprrgHNExSnQxld4Be4=,tag:IZEEYgpBWa5YaDxyjnLh4g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age135kjxpad8nxhac28e2k0clyvlq87m6lwszrs3h5yqwqsqykve3zqx592ht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycHkyYjgrTmxuR1hNZytB
            aEpFeXlya3JnSmxQN0ZZbnVJclZjWjlUVW5JCmdEYlZ0Z3cxWHBHdmZYZkpuYmgr
            Q1N0OEJUeHdxVE13SEpvZlhFUTRwUDQKLS0tIGlLMnNYeWd0WWFXRllZcXFPS1Fi
            M0k4R1RLS21FYWlZa0k5N3dwbTNNVDgKm8VdK0wc0O1QrNKjKekN1ejm9RXxsUKr
            0vmpzs/FQxESyfg4Ct77h7FjDqokOwikKnv094F+5rw2DlgRGocvqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T17:58:44Z"
    mac: ENC[AES256_GCM,data:2TZbKgxRAku5SftyQp/ubpWiP1RLMIS+Fp9BaR/N7gx+RFZ8rx9B7YA1bEEPGrj6Twb+53lR1zTpi0j/UO1feOVLHbbOQeJ/0f42cNQrLKHvDtWX+VM2755iOuBfAW1rhKgKqn+15oMiO/1EyVudJvzAPclp+ZDVF6L3bc22Jss=,iv:Yhs/eCu3uJmj5/pj1Dqw2L5vvTY3SNwhPWzFMQpAUW0=,tag:liLtCM2ePvyk5HsjD6iq1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
