apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:7SQ7HqAujuM=,iv:rpy5kNwcVbqFHyxuYyj2LQFxt212jVa1jlDMBa3aZ6A=,tag:FNsYQUgWCBR+L2sLMZe4ZA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:bILfaicuHhkgNWeW1WiKGFie54Ub0OhJ,iv:ltmKpUp5tUVaYVQt2rv0DvCLwbY1vAQdNSR1QmpDgWw=,tag:xwvbgFLELxddxAblFgU4EQ==,type:str]
kind: Secret
metadata:
    name: linkding-env-secrets
sops:
    age:
        - recipient: age135kjxpad8nxhac28e2k0clyvlq87m6lwszrs3h5yqwqsqykve3zqx592ht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYnVQQWZSUnBJL3hNYnlQ
            aVhvZkpEZzRmajJsNWVhQWZqYWxmMm9JaVZNCkZOckt5Zno1SUVKa3AzdHhlMlps
            dVEyL1JDaVJpTVlXM1hWVmlGQ2pGTmMKLS0tIHJrbWVNcFdHOGpwNUlPRXBua0w3
            MW9IbkdFTFlML29Ha1lxOEh2elpEWWMKeyqjbdJd8Q4TCK4APbeolvbUX6PZMoH9
            7LdVdjg4aFyY48xFZLTrYNwo3qb9tQPdOSn54519OSAWyk0iGzh88Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T21:13:56Z"
    mac: ENC[AES256_GCM,data:RPhibPwchG071GQVDVxdzKOYVl1eMvZRfPWPvIsMMmlZ6/y0J8iZsmtjW6f7T/CMAyFietnYYkGlaF3co0luDDsyaCk+tecwHaYt4hcdXZ8KKc04Sa9dVf8+i+t/shnrVwu7rhbLI18laCNzfFCJAgi5+NBNEV1TpFlGlKDs/3c=,iv:XMqthdxNor310xamJzU8ZYc5FsDUwwR3YVzMsqaex+g=,tag:7Cw6+ZXC5/rbYJg4aZq15A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
