apiVersion: v1
data:
    wg0.conf: ENC[AES256_GCM,data:1PWh0Rjvq2Mv17pYVvAeD4zSULlQjgVdFuwL2Z58KJUNKGhf4sNXIBGARmyshPXfcp+psbBb1h8wMOgv3KYP8/guobJHK5ABim2rOJsnI7qx7RgcoPKBc6+uKuu316eYYof/Z1bZj/3ERX6GiqFG+p9B2dlhXtLBfzusPIa3O+IJYPrr0dub0MAUaUS7H5H+X0ihmz5NQhd9bDmz/LsvabQoMn9ZL1YYpzqG/d5wJCm/2+76qK+EbRIop+PakptmBV2B6BujL7w3uX/hVHhtlou163B2PgMCJKPB69eHDlTRraSRkP/zKTyZGVe/2VT/tT4MeL9Z8/kK95s6oZMGUas8+w5opD0rO/cyMFcEu8wuHnG5nK6vBua4Sv3D3KtX44Qb5mwzJuWPeHISSHH7r4S1fxjNxBs7g/CFC1VquRRet7Ovw1RjnsgATD4hyXnH0Bv/ngOZ5Mty0d49vEYKTQSKKnh+gfSbwX8RsUqs3qViE7cOUa/vou7BGMrKAfJWHALfjEBBB0CJ6xmTy+XRpuY5u03yMkdIcO397lZ+77pTikkRzVqP+/6mywf/1atWqmlcp/SFHwC4CzIl4Tkmvw8xB4D2NFLHgu96d3lugeNgrX8JhFN1XsmEMfC3zM9b03NRhu3nua8vauaffy0aSNLqrQcPu2PbQJobbb0IDbkaxolMajUe0gAhwIBR/VxL6bAq8PZ/ayETZ4bbw5VSyNxHTuYaPwqWCY0+75WPYHufSn5XMpPF3jIKfaOjV1dTjji+EGKMJ2vi8eJSckkgF9qtlC+O7hO3fwbzGiUnhVlUtW64Pgq95Rbn6VzgaolGJG+dEsVAsaYlXQPg0BSpZ+c0f2Gt0/Y7cOvCz92rY3x5RYQG3lMRSQcYj52sfc+0l+YLWqPIwLnl7YdJujwCIoU4rJ6YIyt/o8k0xp9kI4SU2Vikq1dgGc+S04EskR3pA3t6OCqfyJ/tIuTI+4RxJIW5Upb4mwt/JwWka4Mc+y/oStFpdLS5PaSYSRuwKyUKbIbnoArwhlo3g/lgE33Tq0r7I5/XkHGVsaXlwFi/GQJ5hsWXUYnUUWO1IDy+vlzVnmOtQJi7Q3LTFRGE5hqGOihXP5acu4r+AbwY68qTO+/SdnPqTl8mHwGDrJvRH38H17xdZJo3LN3NYLAlzVFKRqo8+LO357ubx5LbU+5iAvKkQzEJmbE7N5X74O5EzFwaHdDqMjJqUg1C1hrabPiwquiVR7jlUVjP5+TaazWqaR5DQ9AiVE5SGpwalywNK72838LPjeHqVo8=,iv:8RWd0H3JZrehSc9LPEVTm/hK87nBTH66WNWkU9au018=,tag:EBYYMPqJyVRk7O30b0oT8Q==,type:str]
kind: Secret
metadata:
    name: wireguard-container-env
sops:
    age:
        - recipient: age135kjxpad8nxhac28e2k0clyvlq87m6lwszrs3h5yqwqsqykve3zqx592ht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaWtYRVg3cXBGUXd3SC91
            bThHM3hTemJWbXBOTDFwemhoS1JXcVZoMEh3CmFlVllrYk1VZUNiRDlpaGNGTmRr
            VjFDTHN1TndlOW9zdU1TQmVmZkM5Sk0KLS0tIEIyOVJjUDVBcTRNWFVXeFhwT1F6
            ZDd2TWNKR095TEZyVzZhVnZjL2k4RmcKPv5KEQIjPgHStm34+sm466eqy5jvZxFn
            PcxHr8Lohjlw1qGOU87RS0Hsjb+GWL8VyIPfHqhFuqw5wyWOlcrifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T09:55:27Z"
    mac: ENC[AES256_GCM,data:lnoM5XMWdayGSmUTXzCSHl7feHjN9fEpYvH2tTFR8XQCvYAJI5krV92igXX4Ahh4MSRq0dAPr8+juLrBxQtvcadrNKiPcjUOvLhMNdK0UJjXcAn8v7sDyRC06TmZqyGqPwQUvx3494/FucWlWQwHzQ0W8cvtCdmYPwjzZe7oAWw=,iv:KN1ihFpRYuM02IUmrxQhyLioIPFb6vf4REqfcNxB2Ns=,tag:4GWJ6+qEw86j/CIwx411Qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
