apiVersion: v1
data:
    wgo.conf.template: ENC[AES256_GCM,data:Yqjwmp+dcw89oS2uAfLU9v41+ooB020P5zNbWFaVIHyCB0fCC5gt71zBTf/h3ndNLLwGmurNlU9UDGyixHVfq3DmLsUDPjaKyYGYNeoaKxax6uoeNeZ0fjdTmW1J3lCTjoKmoEBn+xaSrWDX0YSfqYYsR6UnNQ+wH0bUgL4i/LN3pLkZ0wEWqXD7plIbErI6DRHWs/wA50QpHd3oSPXkKDzZiYEe6G3lnM/BFt6oATTmCR+5ByQx6EuDqyES0ZLoOUpYrg7BiwCVVVYIJxZMEfnvDYb2UFB/YQijRuznLd57GxXDWtpD5fBsJ35iTm6EBPBKdvA7CTKsTt2zoqJmk0Wm5MttyuSsshZa36cQWqr/EyV/WNzhcyKOUMBlL1jS81RqRad7o190dpeCjJOku0XLZjnfynruNC/Nc0kYVX9lkzU8eIKQddgLa7Cn5c4DDlU8z20kUQv+C/2smnK3nWWiSDoZOBUu1STjFqEjW//3ShTVjUdlE5JN/e6rZUqQAELP551Fwu+Zp/1HNKxytO0ssTGb6W5Ll5i53+44K/Eafg/7VbahgPIPuiZZQ6bIqjOs/bGsxfKQSABX1SszecoDI5d3dUFjgXQt+LKqFiIBMx/dJcN4txton39mXNEugQ0/L7acUdnzpm4pArUm43AiDQy2O/prr1yltWIgxSSTZiMkg6wj94mtY6nKg1nnLNjw7IFC2vd9IOUrdj97y6SQs6bTH9tdY+dJhBQJbYYGniRrVo4PhlZ5K7k5lAXL8qkNagm8bAqOSN6YJLAgM/o10PJDEIMpVG/AxW8+poHlcW3jma6Siw3E61czgR6/2ZAakgcsqh8WAbZ4NIgm3fIRQRzINg+xnWm4Re7XRST4nvjgFZlrxMImXczn51/E67LMiLrD2NaCXdibdSXxqKDnbLXAesZ7pKoWLZ7pAZ2wJGhKUdTvpWb6kNSmjgGUXclduq2BwAyTjSRuw+zYYv2U55zOwXEx3jf7u3QyQaL1q+JWWzYnpWFTyK8bNfyWHLcpZ78tdV207kaBcp3ZwyzKqJkQuz6WfehXd9qMSo/OUK6/X98WunlhBSo6EG+0MInMb/Qhjn/GHvhpGqoVEXIz7SlbNYRSQxgOkACvDcXqpIqYkNyE1GgLvbjrjfmLCxvYSHcFEvLTZZ0TuhfIb6p4vzNpgya2inLIDpaGn9eKuU0b72pXCWLqjLVVEXeFPktlF0e9aQFwvMTSTCevY7ZHT0dJsuevhKEfcjeU7tmqh2C1uuQsNMse5bO48IZTgbjwfA==,iv:f1xN4uLYK2AMnzOP4yI3M0EzM90IqfLuOirgqMyfD5U=,tag:QFnlG5MUESfketxHo6PwcA==,type:str]
kind: Secret
metadata:
    name: wireguard-container-env
sops:
    age:
        - recipient: age135kjxpad8nxhac28e2k0clyvlq87m6lwszrs3h5yqwqsqykve3zqx592ht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVkhLYUlGbVQ4RDV6clBt
            ZDlXdVJ0TmlETmFvdGkveXNSUytNaGhUeFQwCkRGckhTWXBPTVgxWGhxZUs2OEFX
            UVNQMldlMHlTTWVocVlIMnhHSllPR2sKLS0tIHJ1Wlh1amV4djZCNSt3a29FbzNZ
            ZmdkVENmRFhYWW5obnpGNWpoQ1h4K1EKEppSoa2sp/OOyjv7V2xZUfbRxZ4Hqa0K
            y+Be8KJl/sT/fwES25nwzF0OasF0JyTtwMC01PdlsmMmJDroFEnPqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T09:25:40Z"
    mac: ENC[AES256_GCM,data:3g/lviGjwdiCS9+So0sC73b8tw6E+4i8OgdD9gjA8wEpl9YV2yygVe87vR82ChYKvbcSOETEsKpeohlKlaLjL+3q0ReOw5xC26Hf34tqtG3B72AHyvEUI19dYqeh8D5nz59sxajQ2eSPqv1hW/YTHIUL8v7lCqomn3l/uNIQVxc=,iv:I3hTR3q9z60j2Lpb2DEPUugLvkAJUNPYTWvp635LO2U=,tag:QmNr9WevH0XzFqdHxXf01Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
