apiVersion: v1
data:
    wg0.conf: ENC[AES256_GCM,data:e/DjZD5BD1I8fSmF60mIDzGuWPb2Z9K1t269oVMpFr3lcLtjr5QfjvPUg/hbrLcrhmXFS2qBaYU6DGogHg4A+Ry18klbOz+ZSHEicnOV6OjJh9DEfXlPg3lf+EMdw4ovt5tG+o0tQwqtDRkDKDl/fZhIXk0fJibW4W5Hw9PJsCs0td2+AHfiQn4cIRiYHrnUzZaNC/qm/gQOwKygLcRmpjBAzqvb/axWGci7j1FndV5Z94uzQQueVSfSd6Hi7DbwXK3YpWBAt7NT7FbzTtxttrAyJB2qQY8KWHjwiHlJgKwxTn2fyN735DMGIK18bJaNhjyy+xbVXa4gEdXn/zRYgJ4RVkL4wXySE0G7fvGJTMqRCrY3g1gBxMbfSqDCIkmg/GQdbb05Eh8JSDSk/JNBBf1AcIh3ds4YrF4OcTxQ2Wiy1Gjluk0QeEXZ8yMV4q8unzzYdCQLQIVGS9A0Y1JZl2I4jLKkh2Cb+ffh2G6iBMTSrUHj8iBZUDUp5p5HOEHb86e7gkTXXD968VXWsPJsyYGEXYF2CG5cJuoNGVGKLmjS5+gxEw/1+AiwItKN3bvWigTng7rmpCOVYN0IjJZHUWxXEacHGm1hFIb+i2rdvoEE1PWiYmSn0OfaRxp05HuhrAJT1q6rmvyWwaOb/RCHHFhRbMKrBzbmGJU305b98NBuWxdVBZn3f7anWs0XmyfLUWHAfHAyQ4+alFJdcv9Cij0GCXFGHy0pLhSgDxwJ3VgLOd/8OTBZ3cIuBuWVMO8a6BxnC5VC9RGJSPSo39ahhl2QS2dkwtQhL55Iyb/5nYuNTk+FUM8JGkq5q55GY2FcE7ZBogl0+puNKs5jNNnypCTw1r5LjfFCNgF3xm2EbCGaNq/z+okpv7wwwcIYVwIUtwL8ftZG+tioN8A0JZC/JfAAhjUn5VELiuKr9gSXimKSOK8BW28VHzUAk4UGE2LEp1xSfMzJsouinmwrFsl5vnsCIbXNz78kjVB22pySVAboSK5KYrN5SabNYR9szU5zVcHMObCmJPtrpfXARDgz8WOEKNOt85cr,iv:JKkFVXMHHct08GjzOZMvZ9b54DlsjHLc/Nb5yd6pRyI=,tag:l8Tub3y9meTJJvcGKo7Wmw==,type:str]
kind: Secret
metadata:
    name: wireguard-container-env
sops:
    age:
        - recipient: age135kjxpad8nxhac28e2k0clyvlq87m6lwszrs3h5yqwqsqykve3zqx592ht
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc040bDhBdHdFVWJkWEVX
            UWFBeXV2eC9CVmVGZWRJanVTUWFKbTRSN1FnCloxWE5Sdko2S2c4R0JzVUZQOHBV
            RDVqQVU2Z2VxN2Z6bHB1eXo0c0twZjAKLS0tIGdxbS9kSmZ6QVRhSVRoNWlLT1Ey
            ZlpPSTA3NW5oVnlYMXBQQ3lQQU94UVUKT26t5E3cN9Bdkh79YahQMN/EgDoNVbOZ
            78+mamu0itPDFfSzQ0YkfDcIVqepHPOOIuQKkmelvAKJdkYivEO13g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T14:36:47Z"
    mac: ENC[AES256_GCM,data:UpNLTaqa6Yle9LwYepVB+ImXHhC9pCfjnZyLjFiqmzlcgd9cpMFfOOGFOqe7CrJaNIVwQF09nL3dCZrHY/HUmKE+V0tHfDSZBTqf6nbGLDVyU1DfLbp7F1mcqkuA8AhnaallYsJqdwcJ67gtqIHie+q1YOnWPlLhMbB4ZdOuFx4=,iv:8s/N6r0h1ckB3PmE9lRi7leRc3+rE2tOcVcx21/mcMw=,tag:jKqqTlbLBhq0jh3Lb3OXqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
